### ISSUE TITLE
`surface::new` should check return value of `bind::SDL_RWFromFile`

### ISSUE THREAD

**Issue by KisaragiEffective** [MikuroXina/rich-sdl2-rust#33]
When [`SDL_RWFromFile`](https://wiki.libsdl.org/SDL2/SDL_RWFromFile) failed (e.g. the file was not found), it returns `NULL` pointer. The current implementation passes its return-ed value without null check, causing "Passed a NULL data source" error from `bind::IMG_LoadTyped_RW`.

**Comment by MikuroXina** [comment]
Thanks! This implementation depends on the null-check by [IMG_LoadTyped_RW](https://github.com/libsdl-org/SDL_image/blob/a861543ab78f5d5e18e6af43964ce8df60cb30b3/IMG.c#L235), but your idea is exact. It should not rely on the library-side check, and ought to pick up the failure as soon as possible.
